FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY app/predict.py .
COPY app/ridge_model.joblib .
COPY app/tfidf_vectorizer.joblib .

EXPOSE 8080
CMD ["uvicorn", "predict:app", "--host", "0.0.0.0", "--port", "8080"]